version: !!str 3

services:
  nifi:
    image: apache/nifi:latest
    depends_on:
     - registry
    env_file:
      - .env
    labels:
     - name=nifi
     - env=production
     - created-by:saeedhosseini
    ports:
      - 8443:8443
    volumes:
      - nifi_data:/opt/nifi/nifi-current/ls-target apache/nifi

  registry:
    image: apache/nifi-registry:latest
    labels:
      - name=nifi-registry
      - env=production
      - created-by:saeedhosseini
    ports:
      - 18080:18080

volumes:
  nifi_data:
